version: '3.4'

services:
  onlinestoredb:
    image: postgres:latest

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile

volumes:
  postgres_data:
    